### ISSUE TITLE
crop_param

### ISSUE THREAD

**Issue by srika91** [shelhamer/fcn.berkeleyvision.org#1]
I have been trying for long time to find out the meaning of "crop_offset" from crop_layer.cpp.
In my datase it throws the following error,

Check failed: bottom[0]->shape(i) - crop_offset >= bottom[1]->shape(i) (2 vs. 3) invalid crop parameters in dimension: 1

In your train.prototxt file you have taken offset as 19 and axis =2.I am trying to train fcn for my own dataset,how to decide these two values is my question.I cannot understand the meaning of these two parameters as well,as I cant find a documentation anywhere.

layer {
  name: "score"
  type: "Crop"
  bottom: "upscore"
  bottom: "data"
  top: "score"
  crop_param {
    axis: 2
    offset: 19
  }
} 

Apologies ,i am confused whether to put this question here or not?

**Comment by shelhamer** [comment]
Please ask Caffe and FCN usage questions on the [caffe-users mailing list](https://groups.google.com/forum/#!forum/caffe-users).

The Crop layer parameters are determined automatically by the coordinate mapping of Python net spec. See the [fcn32s net spec](https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/fcn32s/net.py) and PR BVLC/caffe#3613. You should not define these params yourself, as it has to be done carefully.
